name: Build and Deploy
on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18


      - name: Install and Build server
        if: github.ref == 'refs/heads/test' 
        run: |
          rm -rf node_modules package-lock.json
          npm i -g pnpm
          npm install --legacy-peer-deps
          npm run build:prod

      - name: FTP Deploy server
        if: github.ref == 'refs/heads/test' 
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_pwd }}
          local-dir: ./dist/
          server-dir: /server/nest_start/
          dangerous-clean-slate: true

      - name: Install and Build
        if: github.ref == 'refs/heads/main' 
        run: |
          cd web
          rm -rf node_modules package-lock.json
          npm i -g pnpm
          npm install
          npm run build:h5

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' 
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: ./web/dist/build/h5
          keep_files: true  # 保留已有文件



